# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/base:current
    working_directory: ~/app
    steps:
        - checkout
        - setup_remote_docker:
            version: 20.10.14
        - run: 
            name: Install dependencies
            command: echo "No need to install anything. \n Just build and push the Docker image"
        - run: 
            name: Build and push Docker image
            command: |
              echo "Inside the Build and push Docker image step"
              docker --version 
              docker-compose -f docker-compose-build.yaml build --parallel
              docker tag reverseproxy "$DOCKER_USERNAME"/reverseproxy:v1
              docker tag udagram-api-user "$DOCKER_USERNAME"/udagram-api-user:v1
              docker tag udagram-api-feed "$DOCKER_USERNAME"/udagram-api-feed:v1
              docker tag udagram-frontend "$DOCKER_USERNAME"/udagram-frontend:v1
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN_NAME" --password-stdin
              docker push "$DOCKER_USERNAME"/reverseproxy:v1
              docker push "$DOCKER_USERNAME"/udagram-api-user:v1 
              docker push "$DOCKER_USERNAME"/udagram-api-feed:v1
              docker push "$DOCKER_USERNAME"/udagram-frontend:v1