apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    service: backend-feed
spec:
  selector:
    service: backend-feed
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080