apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  selector:
    service: reverseproxy
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080